# Generated by Django 6.0 on 2026-01-26 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=10, verbose_name='ジャンル名')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(verbose_name='姓')),
                ('first_name', models.CharField(verbose_name='名')),
                ('postal_code', models.CharField(verbose_name='郵便番号')),
                ('phone_number', models.CharField(verbose_name='電話番号')),
                ('image', models.ImageField(default=None, null=True, upload_to='contact_images/', verbose_name='画像')),
                ('mail', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('content', models.TextField(verbose_name='お問い合わせ内容')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日時')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.genre', verbose_name='ジャンル')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='ニュースタイトル')),
                ('image', models.ImageField(default=None, null=True, upload_to='news_images/', verbose_name='画像')),
                ('content', models.TextField(verbose_name='ニュース本文')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日時')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.genre', verbose_name='ジャンル')),
            ],
        ),
    ]
