# Generated by Django 6.0 on 2026-01-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=20, verbose_name='ジャンル名'),
        ),
    ]
