# Generated by Django 6.0 on 2026-01-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='contact_images/', verbose_name='画像'),
        ),
    ]
